apiVersion: v1
kind: Service
metadata:
  name: credit-risk-api-service
  namespace: default
  labels:
    app: credit-risk-api
    tier: backend
spec:
  selector:
    app: credit-risk-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None
