apiVersion: v1
kind: Secret
metadata:
  name: oci-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # Este valor será criado via comando kubectl
---
# Comando para criar o secret:
# kubectl create secret docker-registry oci-registry-secret \
#   --docker-server=sa-saopaulo-1.ocir.io \
#   --docker-username="$TENANCY_NS/$OCI_USER" \
#   --docker-password="$OCI_AUTH_TOKEN" \
#   --namespace=default
